language: node_js
node_js:
  - '0.10'

before_install:
  - git config --global user.name 'Ionitron'
  - git config --global user.email hi@ionicframework.com
  - gem install jekyll
  - npm install -g gulp
script: "./deploy.sh"
branches:
  only:
  - master
exclude:
  - vendor
env:
  matrix:
    secure: aLPluni95Q6fiwxFA4ynv3qEAEMVUmExO0JRsHFU+g9cp6qSHtExt2jSkL0he/BlPM6gT5IwXWJmxvZ3CQx1y/QKitZpQ7//ZcV7SxG67bvWbNb9BriJLFoJVgMRvfNbKRxpttXiP/RzS0yB/nC+u9MnD/lZsnaJP16Wotaw5+4=
